import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/shared';

// The Nunito font is loaded from Google Fonts with the specified
// weights and subsets. The font is then applied to the body element
// using the `--font-nunito` CSS variable.
const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

// For SEO purposes, you can define metadata for the layout
// and pass it to the `metadata` export.
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// The layout component is a wrapper around the page content.
// It can be used to define global styles, layout, and other
// elements that should be present on every page.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main className='min-h-screen'>
          <Header />
          {children}
          </main>
      </body>
    </html>
  );
}
